using System.Diagnostics;
using System.IO;
using QuadClaude.Config;
using QuadClaude.Interop;

namespace QuadClaude.Commands;

public static class LaunchCommand
{
    public static int Execute()
    {
        var config = QuadConfig.Load();
        int windowCount = QuadLauncher.WindowCountForLayout(config?.WindowLayout);

        // Start every launch in the default focus arrangement (quad i in slot i).
        QuadLauncher.ResetFocusOrder();

        // Write launch-env.sh so the launch script knows the runtime config
        if (config != null)
            WriteLaunchEnv(config);

        // Set terminal font size based on monitor resolution
        var fontSize = QuadLauncher.CalculateFontSize(config?.TargetMonitor ?? "largest");
        var profileName = config?.TerminalProfile ?? "Git Bash";
        QuadLauncher.UpdateTerminalFontSize(fontSize, profileName);

        var quadHandles = new List<IntPtr>();

        for (int i = 0; i < windowCount; i++)
        {
            var hWnd = QuadLauncher.LaunchSingleQuad(i, config);
            if (hWnd != IntPtr.Zero)
                quadHandles.Add(hWnd);
        }

        // Spawn a status widget for each quad
        for (int i = 0; i < quadHandles.Count; i++)
        {
            QuadLauncher.SpawnStatusWidget(quadHandles[i], i);
        }

        return 0;
    }

    private static void WriteLaunchEnv(QuadConfig config)
    {
        Directory.CreateDirectory(QuadLauncher.AppDataDir);

        var envPath = Path.Combine(QuadLauncher.AppDataDir, "launch-env.sh");
        var msysProjectsDir = PathHelper.ToMsysPath(config.ProjectsDir);

        var lines = new List<string>
        {
            "# Generated by QuadClaude at launch time",
            $"QUADCLAUDE_PROJECTS_DIR=\"{msysProjectsDir}\"",
            $"QUADCLAUDE_LAYOUT=\"{config.Layout}\""
        };

        if (config.WorktreeBase != null)
        {
            lines.Add($"QUADCLAUDE_WORKTREE_BASE=\"{config.WorktreeBase}\"");
            lines.Add($"QUADCLAUDE_WORKTREE_PATTERN=\"{config.WorktreePattern}\"");
            lines.Add($"QUADCLAUDE_WORKTREE_BASE_BRANCH=\"{config.WorktreeBaseBranch}\"");
        }

        if (!string.IsNullOrWhiteSpace(config.DevServerSubdir))
            lines.Add($"QUADCLAUDE_WORKTREE_SUBDIR=\"{config.DevServerSubdir}\"");

        if (!string.IsNullOrWhiteSpace(config.WorktreeProvisionCommand))
            lines.Add($"QUADCLAUDE_PROVISION_CMD=\"{config.WorktreeProvisionCommand}\"");

        if (config.DedicatedProject != null)
        {
            var targetDir = Path.IsPathRooted(config.DedicatedProject)
                ? config.DedicatedProject
                : Path.Combine(config.ProjectsDir, config.DedicatedProject);
            lines.Add($"QUADCLAUDE_TARGET_DIR=\"{PathHelper.ToMsysPath(targetDir)}\"");
        }

        var escaped = config.QuadLabels.Select(l => $"\"{l}\"");
        lines.Add($"QUADCLAUDE_LABELS=({string.Join(" ", escaped)})");

        File.WriteAllLines(envPath, lines);
    }
}
