import Cocoa

enum LaunchCommand {
    static func execute(appDelegate: AppDelegate) {
        let config = QuadConfig.loadOrDefault()

        // Write launch-env.sh
        writeLaunchEnv(config: config)

        // Launch terminals and position them in 2x2 grid
        DispatchQueue.global(qos: .userInitiated).async {
            let windowIds = TerminalManager.launchQuadGrid(config: config)

            // Create status widgets on the main thread
            DispatchQueue.main.async {
                for (index, windowId) in windowIds.enumerated() {
                    StatusCommand.execute(appDelegate: appDelegate, quadIndex: index, windowId: windowId)
                }
            }
        }
    }

    private static func writeLaunchEnv(config: QuadConfig) {
        let dir = QuadConfig.appSupportDir
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        var lines = [
            "# Generated by QuadClaudeMac at launch time",
            "QUADCLAUDE_PROJECTS_DIR=\"\(config.projectsDir)\"",
            "QUADCLAUDE_LAYOUT=\"\(config.layout)\""
        ]

        if let worktreeBase = config.worktreeBase {
            lines.append("QUADCLAUDE_WORKTREE_BASE=\"\(worktreeBase)\"")
        }

        if let dedicatedProject = config.dedicatedProject {
            let targetDir: String
            if dedicatedProject.hasPrefix("/") {
                targetDir = dedicatedProject
            } else {
                targetDir = (config.projectsDir as NSString).appendingPathComponent(dedicatedProject)
            }
            lines.append("QUADCLAUDE_TARGET_DIR=\"\(targetDir)\"")
        }

        let escapedLabels = config.quadLabels.map { "\"\($0)\"" }.joined(separator: " ")
        lines.append("QUADCLAUDE_LABELS=(\(escapedLabels))")

        let envURL = dir.appendingPathComponent("launch-env.sh")
        let content = lines.joined(separator: "\n") + "\n"
        try? content.write(to: envURL, atomically: true, encoding: .utf8)
    }
}
